version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  backend:
    build: ./backend
    ports:
      - "8000:8000"
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_DATABASE: 'tftools-db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '0000'
    ports:
      - "3306:3306"
    volumes:
      - ./database/tftools_db_script.sql:/docker-entrypoint-initdb.d/tftools_db_script.sql